#
# mina protocol docker-compose config
#

version: '3.9'
services:

  mainnet:
    profiles: ["mainnet"]
    #image: minaprotocol/mina-daemon-baked:${MINA_TAG_MAIN}
    #image: gcr.io/o1labs-192920/mina-daemon-baked:${MINA_TAG_MAIN}
    image: minaprotocol/mina-daemon:${MINA_TAG_MAIN}
    command: daemon ${DAEMON_OPTS_MAINNET}
    environment:
      - CODA_PRIVKEY_PASS=${MINA_PRIVKEY_PASS}
      - MINA_PRIVKEY_PASS=${MINA_PRIVKEY_PASS}
      - UPTIME_PRIVKEY_PASS=${MINA_PRIVKEY_PASS}
      - MINA_PUBLIC_KEY=${MINA_PUBLIC_KEY}
      - SERVER_HOSTNAME=${SERVER_HOSTNAME}
      - IPV4_NETWORK=${IPV4_NETWORK:-172.25.0}
    volumes:
      - ./keys:/keys:ro
      - ./.mina-config/mainnet/:/root/.mina-config:rw
      - ./etc/mainnet/daemon.json:/root/.mina-config/daemon.json:ro
    ports:
      - "${MINA_BIND:-0.0.0.0}:${MINA_PORT_MAIN:-8302}:${MINA_PORT_MAIN:-8302}"
      - "${MINA_BIND:-0.0.0.0}:3085:3085"
    restart: always
    logging:
      options:
        max-size: ${MINA_LOG_MAX_SIZE:-4m}
        max-file: ${MINA_LOG_MAX_FILE:-10}
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=${SYSCTL_IPV6_DISABLED:-0}
    networks:
      m_net:
        aliases:
          - m-main
          - m-main.local

  mainnet_archive:
    profiles: ["mainnet-archive"]
    depends_on:
      - db
    image: minaprotocol/mina-archive:${MINA_TAG_ARCH}
    command: run ${DAEMON_OPTS_MAINNET_ARCHIVE}
    environment:
      - SERVER_HOSTNAME=${SERVER_HOSTNAME}
      - IPV4_NETWORK=${IPV4_NETWORK:-172.25.0}
    restart: always
    logging:
      options:
        max-size: ${MINA_LOG_MAX_SIZE:-4m}
        max-file: ${MINA_LOG_MAX_FILE:-10}
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=${SYSCTL_IPV6_DISABLED:-0}
    networks:
      m_net:
        aliases:
          - archive-mainnet
          - archive-mainnet.local

  devnet:
    profiles: ["devnet"]
    image: minaprotocol/mina-daemon-baked:${MINA_TAG_DEV}
    command: daemon ${DAEMON_OPTS_DEVNET}
    environment:
      - CODA_PRIVKEY_PASS=${MINA_PRIVKEY_PASS}
      - MINA_PUBLIC_KEY=${MINA_PUBLIC_KEY}
      - SERVER_HOSTNAME=${SERVER_HOSTNAME}
      - IPV4_NETWORK=${IPV4_NETWORK:-172.25.0}
    volumes:
      - ./keys:/keys:ro
      - ./.mina-config/devnet/:/root/.mina-config:rw
      - ./etc/devnet/daemon.json:/root/.mina-config/daemon.json:ro
    ports:
      - "${MINA_BIND:-0.0.0.0}:${MINA_PORT_DEV:-18302}:${MINA_PORT_DEV:-18302}"
    restart: always
    logging:
      options:
        max-size: ${MINA_LOG_MAX_SIZE:-4m}
        max-file: ${MINA_LOG_MAX_FILE:-10}
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=${SYSCTL_IPV6_DISABLED:-0}
    networks:
      m_net:
        aliases:
          - m-dev
          - m-dev.local

  devnet_archive:
    profiles: ["devnet-archive"]
    depends_on:
      - db
    image: minaprotocol/mina-archive:${MINA_TAG_ARCH}
    command: run ${DAEMON_OPTS_DEVNET_ARCHIVE}
    environment:
      - SERVER_HOSTNAME=${SERVER_HOSTNAME}
      - IPV4_NETWORK=${IPV4_NETWORK:-172.25.0}
    restart: always
    logging:
      options:
        max-size: ${MINA_LOG_MAX_SIZE:-4m}
        max-file: ${MINA_LOG_MAX_FILE:-10}
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=${SYSCTL_IPV6_DISABLED:-0}
    networks:
      m_net:
        aliases:
          - archive-devnet
          - archive-devnet.local

  db:
    profiles: ["database"]
    image: postgres:12.6
    volumes:
      - ./etc/init/init_mina_archive_mainnet.sql:/docker-entrypoint-initdb.d/init_mina_archive_mainnet.sql
      - ./etc/init/init_mina_archive_devnet.sql:/docker-entrypoint-initdb.d/init_mina_archive_devnet.sql
      - ./db/postgresql/:/var/lib/postgresql/data/:rw
      - ./etc/postgresql/:/etc/postgresql/conf.d:ro
    environment:
      - TZ=${TZ}
      - DEBUG=false
      - POSTGRES_PASSWORD=${POSTGRES_ROOT}
      - POSTGRES_HOST_AUTH_METHOD=trust
    restart: always
    ports:
      - "${POSTGRES_PORT:-127.0.0.1:5432}:5432"
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=${SYSCTL_IPV6_DISABLED:-0}
    networks:
      m_net:
        aliases:
          - postgresql
          - postgresql.local
          - db.local

  mainnet_sidecar:
    profiles: ["mainnet"]
    depends_on:
      - mainnet
    image: minaprotocol/mina-bp-stats-sidecar:latest
    volumes:
      - ./etc/sidecar/mina-sidecar-config.json:/etc/mina-sidecar.json:ro
    restart: always
    logging:
      options:
        max-size: ${MINA_LOG_MAX_SIZE:-4m}
        max-file: ${MINA_LOG_MAX_FILE:-10}
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=${SYSCTL_IPV6_DISABLED:-0}
    networks:
      m_net:
        aliases:
          - sidecar
          - sidecar.local

  mainnet_snark_stopper:
    profiles: ["snark-stopper"]
    depends_on:
      - mainnet
    image: c29r3/snark-stopper:latest
    volumes:
      - ./etc/snark-stopper/config.yml:/mina/config.yml:ro
      - ./logs/snark_stopper.log:/mina/snark_stopper.log:rw
    restart: always
    logging:
      options:
        max-size: ${MINA_LOG_MAX_SIZE:-4m}
        max-file: ${MINA_LOG_MAX_FILE:-10}
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=${SYSCTL_IPV6_DISABLED:-0}
    networks:
      m_net:
        aliases:
          - sw-stopper
          - sw-stopper.local

  #
  # mina protocol docker-compose additional config for performance dashboard
  # Check https://github.com/dsrvlabs/mina-performance-dashboard for more info
  #
  prometheus:
    profiles: ["dashboard"]
    image: prom/prometheus
    environment:
      - SERVER_HOSTNAME=${SERVER_HOSTNAME}
    volumes:
      - ./etc/dashboard/prometheus-mina.yml:/etc/prometheus/prometheus.yml:ro
      - ./db/prometheus:/prometheus:rw
    ports:
      - "${MINA_BIND:-127.0.0.1}:${PROMETHEUS_PORT:-9090}:${PROMETHEUS_PORT:-9090}"
    restart: always
    logging:
      options:
        max-size: ${MINA_LOG_MAX_SIZE:-4m}
        max-file: ${MINA_LOG_MAX_FILE:-10}
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=${SYSCTL_IPV6_DISABLED:-0}
    networks:
      m_net:
        aliases:
          - prometheus
          - prometheus.local

  node_exporter:
    profiles: ["dashboard"]
    image: quay.io/prometheus/node-exporter:latest
    command:
      - '--path.rootfs=/host'
    volumes:
      - '/:/host:ro,rslave'
    pid: host
    restart: unless-stopped
    logging:
      options:
        max-size: ${MINA_LOG_MAX_SIZE:-4m}
        max-file: ${MINA_LOG_MAX_FILE:-10}
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=${SYSCTL_IPV6_DISABLED:-0}
    networks:
      m_net:
        aliases:
          - n-exporter
          - n-exporter.local

  grafana:
    profiles: ["dashboard"]
    image: grafana/grafana
    environment:
      - GF_INSTALL_PLUGINS=fifemon-graphql-datasource
      - SERVER_HOSTNAME=${SERVER_HOSTNAME}
    volumes:
      - ./db/grafana:/var/lib/grafana:rw
    ports:
      - "${MINA_BIND:-0.0.0.0}:${GRAFANA_PORT:-3000}:3000"
    restart: always
    logging:
      options:
        max-size: ${MINA_LOG_MAX_SIZE:-4m}
        max-file: ${MINA_LOG_MAX_FILE:-10}
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=${SYSCTL_IPV6_DISABLED:-0}
    networks:
      m_net:
        aliases:
          - grafana
          - grafana.local

networks:
  m_net:
    driver: bridge
    enable_ipv6: false
    ipam:
      driver: default
      config:
        - subnet: ${IPV4_NETWORK:-172.25.0}.0/24
